[env:sakurapi-mv]
extends = esp32s3_base
board = esp32-s3-devkitc-1
; board_build.f_cpu = 240000000L
; board_upload.flash_size = 8MB
board_build.partitions = partition-table-8MB.csv
; board_upload.maximum_size = 8388608
upload_protocol = esptool

build_unflags = -flto

build_flags = 
  ${esp32s3_base.build_flags}
  -D SAKURAPI_MV
  -I variants/esp32s3/sakurapi-mv
  -D BOARD_HAS_PSRAM
  -D PRIVATE_HW
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_LR11X0=1
  -DMESHTASTIC_EXCLUDE_RANGETEST=1
  -DMESHTASTIC_EXCLUDE_DETECTIONSENSOR=1
  -DMESHTASTIC_EXCLUDE_SERIAL=1
  -DHAS_BBQ10_KEYBOARD=0
  -DHAS_MPR121_KEYBOARD=0
  -DHAS_TCA8418_KEYBOARD=0
  -DMESHTASTIC_EXCLUDE_ATAK=1
  -D EMOTE_COLOR_INCLUDE_CURRENCY=1
  -D EMOTE_COLOR_MINIMAL=1
  ; -DHAS_SENSOR=0
  ; -DHAS_TFT=1
  ; -D LGFX_DRIVER=LGFX_GENERIC
  ; -D GFX_DRIVER_INC=\"graphics/LGFX/LGFX_GENERIC.h\"

lib_deps =
  ${esp32s3_base.lib_deps}
  ; ${device-ui_base.lib_deps}
  # renovate: datasource=custom.pio depName=LovyanGFX packageName=lovyan03/library/LovyanGFX
  lovyan03/LovyanGFX@1.2.19